---
# user setup
- name: group ~> create for openhab
  group:
    name: openhab
    state: present

- name: user ~> create for openhab
  user:
    name: openhab
    comment: Openhab System User
    append: yes
    groups: openhab
    state: present
    system: true

- include: "repo-{{ ansible_os_family }}.yml"

# @todo: fix what happen on ubuntu bionic error
- name: package ~> install zulu-8
  package:
    name: zulu-8
    state: present
    update_cache: yes
  register: zulu8_stat
  failed_when: zulu8_stat.rc > 1000

- name: set_fact ~> openhab install addons packages
  set_fact:
    openhab_packages: "{{ openhab_packages + [ 'openhab2-addons' ] }}"
  when: openhab_install_addons

- name: pacakage ~> install openhab packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ openhab_packages }}"

- name: template ~> configure /etc/default/openhab2
  template:
    src: files/openhab-default.conf
    dest: /etc/default/openhab2
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: service ~> start openhab
  service:
    name: openhab2
    state: started
