---
- include: setup-config.yml

- include: "repo-{{ ansible_os_family }}.yml"

- name: fact ~> set java in arm
  set_fact:
    _openhab_zulu_package: zulu-embedded-8
  when: ansible_machine.find('arm') != -1

- name: package ~> install zulu-8
  package:
    name: "{{ _openhab_zulu_package }}"
    state: present

- name: set_fact ~> openhab install addons packages
  set_fact:
    openhab_packages: "{{ openhab_packages + [ 'openhab2-addons' ] }}"
  when: openhab_install_addons

- name: package ~> install openhab packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ openhab_packages }}"

- name: service ~> start openhab
  service:
    name: openhab2
    state: started
    enabled: yes

# begin custom config
- name: stat ~> gather for userdata/etc
  stat:
    path: /srv/openhab/userdata/etc
  register: userdata_etc

- name: copy ~> copy basic userdata
  copy:
    dest: /srv/openhab/userdata
    src: /var/lib/openhab2/etc
    owner: openhab
    group: openhab
    mode: '0775'
    remote_src: yes
  when: not userdata_etc.stat.exists

- name: template ~> configure /etc/default/openhab2
  template:
    src: openhab-default.conf
    dest: /etc/default/openhab2
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
    - openhab restart

- name: configure user
  include: nginx-user.yml
  when: openhab_nginx_users|length > 0
