- name: command ~> list existing apt-key
  command: apt-key list
  register: zulu_apt_key_stat

- name: command ~> add apt key for zulu
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xB1998361219BD9C9
  when: zulu_apt_key_stat.stdout.find('azulsystems') == -1

- name: apt_repository ~> add ubuntu
  apt_repository:
    filename: 'zulu'
    repo: deb http://repos.azulsystems.com/ubuntu stable main
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: apt_repository ~> add debian
  apt_repository:
    filename: 'zulu'
    repo: deb http://repos.azulsystems.com/debian stable main
    state: present
  when: ansible_distribution == 'Debian'

- name: apt_key ~> add openhab
  apt_key:
    url: https://bintray.com/user/downloadSubjectPublicKey?username=openhab
    state: present

- name: apt_repository ~> add openhab
  apt_repository:
    filename: 'openhab'
    repo: deb https://dl.bintray.com/openhab/apt-repo2 stable main
    state: present
  when: ansible_os_family == 'Debian'
