---
- name: Converge
  hosts: all
  pre_tasks:

    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: file ~> generate deploy dir
      file:
        path: /srv/deploy
        state: directory
        owner: root
        group: root
        mode: '0644'

    - name: file ~> generate openssh dir
      copy:
        src: ./files/development.rsa
        dest: /srv/deploy/openhab.rsa
        owner: root
        group: root
        mode: '0600'

    - name: configure openssl
      include: include/openssl.yml

  roles:
    - role: openhab

  vars:
    openhab_install_addons: false
    openhab_conf: /srv/openhab/config
    openhab_userdata: /srv/openhab/userdata
    openhab_config_repo: git@bitbucket.org:kilip/openhab-default-config.git
    openhab_config_ssh_keyfile: /srv/deploy/openhab.rsa
    openhab_config_owner: toni

    openhab_configure_nginx: true
    openhab_nginx_allow:
      - 10.0.0.0/24
    openhab_nginx_servername: localhost
    openhab_nginx_certificate: '/etc/nginx/cert/openhab.crt'
    openhab_nginx_certificate_key: '/etc/nginx/cert/openhab.pem'
