---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint

platforms:
- name: instance
  image: "${MOLECULE_DISTRO:-centos:7}"
  published_ports:
    - 0.0.0.0:8443:8443
    - 0.0.0.0:8080:8080

provisioner:
  name: ansible
  lint:
    name: ansible-lint

verifier:
  name: testinfra
  lint:
    name: flake8
