---
- name: Converge
  hosts: all
  pre_tasks:
    - name: pakcage ~> add software properties
      package: "{{ item }}"
      state: present
      loop:
      - software-properties-common
      - apt-transport-https
  roles:
    - role: openhab
  vars:
    openhab_install_addons: true
