---
- name: Converge
  hosts: all
  pre_tasks:
    - name: pakcage ~> add software properties
      package:
        name: "{{ item }}"
        state: present
        loop:
        - software-properties-common
        - apt-transport-https
        when: ansible_os_family == 'Debian'
  roles:
    - role: openhab
  vars:
    openhab_install_addons: true
